### ISSUE TITLE
Updates for ActiveRecord 7.1.0 needed?

### ISSUE THREAD

**Issue by ekampp** [falconed/pgreset#7]
Hey. 

First off, thanks for a great gem. I recently reflexively installed it in my project on my Rails 7.1.0.rc1 branch.

This caused this error when running `rails db:reset`:

```
bin/rails aborted!
NameError: undefined local variable or method `establish_master_connection' for an instance of ActiveRecord::Tasks::PostgreSQLDatabaseTasks

Tasks: TOP => db:drop:_unsafe
```

**Comment by dafalcon** [comment]
Thank you for the kind words and the bug report!  I just pushed version 0.4, which I believe should fix the issue and still maintain backward compatibility with older rails versions.  Please let me know if you run into anything else.  So happy to hear your pgreset install is reflexive :)
